### ISSUE TITLE
Touch not working at Surface Pro 4

### ISSUE THREAD

**Issue by welllini** [Xiashangning/IPTSDaemon-old#19]
HeIlo,

i installed like you discribed. No error in install_IPTSDaemon, checked, all Files there.
If i run manually get error.
bigs@BigSdeMacBook-Pro bin % IPTSDaemon
[13:32:54.347] [error] Could not find IntelPreciseTouchStylusDriver!
Latest BigSure and IPTSDaemon installed.
If i run sudo dmesg | grep -E "SurfaceS|SurfaceH|SurfaceM|IntelP"
asking for Password, but no other output.
i install the debug.kext in OC Kextfolder, and put it into conf.plist
So what else can i do?
Thanks

**Comment by seven-of-eleven** [comment]
@welllini to be clear you have the latest BigSurface and IPTSDaemon installed? Did you check if you BigSurface kext was loading? Can you upload your EFI folder?

**Comment by welllini** [comment]
Hello
i checkedi it twice, Bigsure and IPTSDaemon are the latest. How can i check if the kext are loaded?
I can't load the EFI it is 26MB as .zip File.
Thanks alot.

**Comment by xealstorm** [comment]
@welllini Have you tried with BigSurface 6.3? 
i have a different device (SP7) but touch on 6.3 works more consistently to me.

**Comment by welllini** [comment]
I tried 6.3 and now 6.4 but no touch. i use OCAT and under Kernel all Kext are Green.

**Comment by welllini** [comment]
Hi,  i found here[ ](https://github.com/badstorm/surface-pro-7-opencore) an EFI for SF7 ( i know it is a complete different System) but my SF4 is booting and the touch is working.  i used the BS.kext and also the ACPI step by step, but no touch. So i know at least my Files loaded correct. 
I will keep on.

**Comment by seven-of-eleven** [comment]
You can check if your kexts are loaded using `kextstat` on the terminal. That should list them all (use grep to narrow the list if you like).

Also check `brew list` on the command line to ensure `fmt inih` are both installed.

Can you upload just your config.plist file?

**Comment by welllini** [comment]
I checked with kextsat but Bigsure.kext not loaded.  fmt and inih loaded.
[config.plist.zip](https://github.com/Xiashangning/IPTSDaemon-old/files/10755185/config.plist.zip)

**Comment by welllini** [comment]
if i use this a EFI Folder from SF7 ( i know it is a different System, but my SF4 is booting ) the Touch is working and BigSure is loaded. I put the cinf from SF7 too.
[config.plist.zip](https://github.com/Xiashangning/IPTSDaemon-old/files/10755395/config.plist.zip)

**Comment by seven-of-eleven** [comment]
Taking a quick look at your config.plist file. 
1. If you've updated to the latest BigSurface.kext, you haven't updated the config.plist file to reflect it. You're missing the BigSurfaceHIDDriver.kext included in the latest BigSurface.kext. 
2.  BigSurface kexts are in the wrong order.
3. There are a lot of other things going on in your config.plist that I'm not sure you need but assume you've included for a reason.
4. You have a USBMap.kext, you should remove or disable USBInjectAll.kext.

There are a lot of other differences b/w the two configs. Open them both up in Propertree and compare them. I don't think this is an issue with the kext or IPTSDaemon, but rather fixing up your EFI.

Best of luck.

**Comment by welllini** [comment]
i didi the update to 6.4 before, but no help. so i try to use the BigSure.kext from the EFI from SF7 witch is working at my SF if i boot with this EFI. If i remove the USBInjedctall.kext my Dogginstation is not working anymore. if i remove the USBMap.kext, the CardReader not seen. So i need both !
I will close this case, because i will get an SF7 next week.
Thanks alot for your help.
